# Generated by Django 4.2.1 on 2023-06-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedbacktable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=40)),
                ('age', models.IntegerField(default='')),
                ('dining', models.CharField(default='', max_length=30)),
                ('recommend', models.CharField(default='', max_length=30)),
                ('favorite', models.CharField(default='', max_length=30)),
                ('improve', models.CharField(default='', max_length=30)),
                ('comment', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
