# Generated by Django 4.2.1 on 2023-06-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=30)),
                ('lastname', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=40)),
                ('phone', models.CharField(default='', max_length=30)),
                ('date', models.DateField(default='', max_length=30)),
                ('time', models.TimeField(default='', max_length=30)),
                ('counts', models.IntegerField(default='')),
                ('additional', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
