# Generated by Django 4.2.1 on 2023-06-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_remove_bookingtable_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtable',
            name='name',
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='firstname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='lastname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
